package com.mycompany.smartinventorymanagementsystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mokhtar
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnProducts_dashboard = new javax.swing.JButton();
        btnSuppliers_dashboard = new javax.swing.JButton();
        btnReports_dashboard = new javax.swing.JButton();
        Status_Bar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 550));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel2.setText("Control Panel");

        btnProducts_dashboard.setText("Products");
        btnProducts_dashboard.addActionListener(this::btnProducts_dashboardActionPerformed);

        btnSuppliers_dashboard.setText("Suppliers");
        btnSuppliers_dashboard.addActionListener(this::btnSuppliers_dashboardActionPerformed);

        btnReports_dashboard.setText("Reports");
        btnReports_dashboard.addActionListener(this::btnReports_dashboardActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Status_Bar)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuppliers_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProducts_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReports_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel2)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(btnProducts_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuppliers_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReports_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(Status_Bar)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuppliers_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliers_dashboardActionPerformed
        // TODO add your handling code here:
        Suppliersform sup = new Suppliersform(); // اتأكد من الاسم بالظبط زي ما هو في المشروع
sup.setVisible(true);
sup.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSuppliers_dashboardActionPerformed

    private void btnProducts_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducts_dashboardActionPerformed
        // TODO add your handling code here:
        ProductsForm prd = new ProductsForm(); // إنشاء نسخة من صفحة المنتجات
prd.setVisible(true); // إظهار الصفحة
prd.setLocationRelativeTo(null); // عشان تفتح في نص الشاشة بالضبط
    }//GEN-LAST:event_btnProducts_dashboardActionPerformed

    private void btnReports_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReports_dashboardActionPerformed
        // TODO add your handling code here:
        ReportsForme rep = new ReportsForme(); // لاحظ إن الاسم عندك فيه حرف e في الآخر
rep.setVisible(true);
rep.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReports_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status_Bar;
    private javax.swing.JButton btnProducts_dashboard;
    private javax.swing.JButton btnReports_dashboard;
    private javax.swing.JButton btnSuppliers_dashboard;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
