/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smartinventorymanagementsystem;

import SmartInventoryManagementSystem.MyConnection;

/**
 *
 * @author mokhtar
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername_login = new javax.swing.JLabel();
        jTextFieldUsername_login = new javax.swing.JTextField();
        txtPassword_login = new javax.swing.JLabel();
        jPasswordField1_login = new javax.swing.JPasswordField();
        jButtonSignin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUsername_login.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        txtUsername_login.setText("Username");

        jTextFieldUsername_login.addActionListener(this::jTextFieldUsername_loginActionPerformed);

        txtPassword_login.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        txtPassword_login.setText("Password");

        jPasswordField1_login.setText("jPasswordField1");

        jButtonSignin.setText("Sign in");
        jButtonSignin.addActionListener(this::jButtonSigninActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername_login, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldUsername_login)
                    .addComponent(jPasswordField1_login, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername_login)
                    .addComponent(jTextFieldUsername_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword_login)
                    .addComponent(jPasswordField1_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButtonSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsername_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsername_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsername_loginActionPerformed

    private void jButtonSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSigninActionPerformed

        // TODO add your handling code here:
        
        try {
    // 1. استدعاء الاتصال من كلاس MyConnection
    // ملحوظة: لو MyConnection في باكيدج تانية، نتبينز هيطلب منك Import
    java.sql.Connection con = MyConnection.getConnection();
    
    // 2. تجهيز الاستعلام
    String sql = "SELECT * FROM users WHERE username=? AND password=?";
    java.sql.PreparedStatement ps = con.prepareStatement(sql);
    
    // 3. ربط الخانات اللي في الفورم بالكود
    // تأكد إن jTextField1 هو بتاع اليوزر و jPasswordField1 بتاع الباسورد
    ps.setString(1, jTextFieldUsername_login.getText()); 
    ps.setString(2, String.valueOf(jPasswordField1_login.getPassword()));
    
    // 4. تشغيل البحث
    java.sql.ResultSet rs = ps.executeQuery();
    
    if (rs.next()) {
        // لو لقى اليوزر (admin / admin123)
        javax.swing.JOptionPane.showMessageDialog(null, "تم تسجيل الدخول بنجاح!");
        
        // فتح الصفحة الرئيسية وقفل اللوجن
        DashboardForm dash = new DashboardForm();
        dash.setVisible(true);
        this.dispose(); 
    } else {
        // لو البيانات غلط
        javax.swing.JOptionPane.showMessageDialog(null, "اسم المستخدم أو كلمة السر خطأ", "تنبيه", 2);
    }
    
}
        catch (Exception e) {
    // لو فيه مشكلة في السيرفر أو القاعدة
    javax.swing.JOptionPane.showMessageDialog(null, "مشكلة في الاتصال: " + e.getMessage());

    }//GEN-LAST:event_jButtonSigninActionPerformed
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSignin;
    private javax.swing.JPasswordField jPasswordField1_login;
    private javax.swing.JTextField jTextFieldUsername_login;
    private javax.swing.JLabel txtPassword_login;
    private javax.swing.JLabel txtUsername_login;
    // End of variables declaration//GEN-END:variables
}
