/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smartinventorymanagementsystem;

/**
 *
 * @author mokhtar
 */
public class Suppliersform extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Suppliersform.class.getName());

    /**
     * Creates new form Suppliersform
     */
    public Suppliersform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_suppliername_supplierform = new javax.swing.JLabel();
        jLabel2_phone_supplierform = new javax.swing.JLabel();
        jLabel3_address_supplierform = new javax.swing.JLabel();
        jTextField1_suppliername_supplierform = new javax.swing.JTextField();
        jTextField2_phone_supplierform = new javax.swing.JTextField();
        jTextField3_address_supplierform = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_supplierform = new javax.swing.JTable();
        jButton1_save_supplierform = new javax.swing.JButton();
        jButton2_update_supplierform = new javax.swing.JButton();
        jButton3_delete_supplierform = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(743, 489));

        jLabel1_suppliername_supplierform.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        jLabel1_suppliername_supplierform.setText("Supplier Name");

        jLabel2_phone_supplierform.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel2_phone_supplierform.setText("Phone");

        jLabel3_address_supplierform.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel3_address_supplierform.setText("Address");

        jTextField1_suppliername_supplierform.addActionListener(this::jTextField1_suppliername_supplierformActionPerformed);

        jTextField2_phone_supplierform.addActionListener(this::jTextField2_phone_supplierformActionPerformed);

        jTable1_supplierform.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1_supplierform);

        jButton1_save_supplierform.setBackground(new java.awt.Color(0, 204, 51));
        jButton1_save_supplierform.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_save_supplierform.setText("Save");

        jButton2_update_supplierform.setBackground(new java.awt.Color(51, 102, 255));
        jButton2_update_supplierform.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_update_supplierform.setText("Update");

        jButton3_delete_supplierform.setBackground(new java.awt.Color(204, 0, 0));
        jButton3_delete_supplierform.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_delete_supplierform.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1_suppliername_supplierform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3_address_supplierform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2_phone_supplierform, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1_suppliername_supplierform)
                    .addComponent(jTextField2_phone_supplierform)
                    .addComponent(jTextField3_address_supplierform, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3_delete_supplierform)
                .addGap(18, 18, 18)
                .addComponent(jButton2_update_supplierform)
                .addGap(18, 18, 18)
                .addComponent(jButton1_save_supplierform)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_suppliername_supplierform)
                    .addComponent(jTextField1_suppliername_supplierform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_phone_supplierform)
                    .addComponent(jTextField2_phone_supplierform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3_address_supplierform)
                    .addComponent(jTextField3_address_supplierform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_save_supplierform)
                    .addComponent(jButton2_update_supplierform)
                    .addComponent(jButton3_delete_supplierform))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_suppliername_supplierformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_suppliername_supplierformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_suppliername_supplierformActionPerformed

    private void jTextField2_phone_supplierformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_phone_supplierformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_phone_supplierformActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Suppliersform().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_save_supplierform;
    private javax.swing.JButton jButton2_update_supplierform;
    private javax.swing.JButton jButton3_delete_supplierform;
    private javax.swing.JLabel jLabel1_suppliername_supplierform;
    private javax.swing.JLabel jLabel2_phone_supplierform;
    private javax.swing.JLabel jLabel3_address_supplierform;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_supplierform;
    private javax.swing.JTextField jTextField1_suppliername_supplierform;
    private javax.swing.JTextField jTextField2_phone_supplierform;
    private javax.swing.JTextField jTextField3_address_supplierform;
    // End of variables declaration//GEN-END:variables
}
