/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.smartinventorymanagementsystem;

/**
 *
 * @author mokhtar
 */
public class UserForme extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserForme.class.getName());

    /**
     * Creates new form UserForme
     */
    public UserForme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_userform = new javax.swing.JTable();
        jLabel1_Userform_username = new javax.swing.JLabel();
        jLabel2_userform_password = new javax.swing.JLabel();
        jLabel3_userform_role = new javax.swing.JLabel();
        jTextField1_userform_username = new javax.swing.JTextField();
        jPasswordField1_userform_password = new javax.swing.JPasswordField();
        jComboBox1_userform_role = new javax.swing.JComboBox<>();
        jButton1_userform_save = new javax.swing.JButton();
        jButton2_userform_update = new javax.swing.JButton();
        jButton3_userform_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1_userform.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username ", "Password", "Role"
            }
        ));
        jScrollPane1.setViewportView(jTable1_userform);

        jLabel1_Userform_username.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel1_Userform_username.setText("Username");

        jLabel2_userform_password.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel2_userform_password.setText("Password");

        jLabel3_userform_role.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        jLabel3_userform_role.setText("Role");

        jPasswordField1_userform_password.setText("jPasswordField1");

        jComboBox1_userform_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jComboBox1_userform_role.addActionListener(this::jComboBox1_userform_roleActionPerformed);

        jButton1_userform_save.setBackground(new java.awt.Color(0, 204, 51));
        jButton1_userform_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_userform_save.setText("Save");

        jButton2_userform_update.setBackground(new java.awt.Color(51, 102, 255));
        jButton2_userform_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_userform_update.setText("Update");

        jButton3_userform_delete.setBackground(new java.awt.Color(204, 0, 0));
        jButton3_userform_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_userform_delete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_Userform_username)
                    .addComponent(jLabel2_userform_password)
                    .addComponent(jLabel3_userform_role, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1_userform_username)
                        .addComponent(jPasswordField1_userform_password, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addComponent(jComboBox1_userform_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3_userform_delete)
                .addGap(18, 18, 18)
                .addComponent(jButton2_userform_update)
                .addGap(18, 18, 18)
                .addComponent(jButton1_userform_save)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_Userform_username)
                    .addComponent(jTextField1_userform_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_userform_password)
                    .addComponent(jPasswordField1_userform_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_userform_role)
                    .addComponent(jComboBox1_userform_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_userform_save)
                    .addComponent(jButton2_userform_update)
                    .addComponent(jButton3_userform_delete))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_userform_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_userform_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_userform_roleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserForme().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_userform_save;
    private javax.swing.JButton jButton2_userform_update;
    private javax.swing.JButton jButton3_userform_delete;
    private javax.swing.JComboBox<String> jComboBox1_userform_role;
    private javax.swing.JLabel jLabel1_Userform_username;
    private javax.swing.JLabel jLabel2_userform_password;
    private javax.swing.JLabel jLabel3_userform_role;
    private javax.swing.JPasswordField jPasswordField1_userform_password;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_userform;
    private javax.swing.JTextField jTextField1_userform_username;
    // End of variables declaration//GEN-END:variables
}
